name: Lint
description: Runs statix and deadnix against Nix files

runs:
  using: composite
  steps:
    - run: nix run nixpkgs#statix -- check .
      shell: bash
    - run: nix run nixpkgs#deadnix -- --fail .
      shell: bash
