{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./bluetuith.nix
    ./bottom.nix
    ./delta.nix
    ./direnv.nix
    ./duf.nix
    ./dust.nix
    ./eza.nix
    ./fd.nix
    ./firefox.nix
    ./fish.nix
    ./fuzzel.nix
    ./git.nix
    ./ironbar.nix
    ./just.nix
    ./mangohud.nix
    ./neovim.nix
    ./niri
    ./prismlauncher.nix
    ./procs.nix
    ./ripgrep.nix
    ./starship.nix
    ./swaylock.nix
    ./tmux.nix
    ./vesktop.nix
    ./wl-clipboard.nix
    ./xwayland-satellite.nix
  ];
}
