{
  imports = [
    ./bat.nix
    ./bluetuith.nix
    ./bottom.nix
    ./delta.nix
    ./direnv.nix
    ./duf.nix
    ./dust.nix
    ./eza.nix
    ./fd.nix
    ./fish
    ./foot
    ./fuzzel
    ./git
    ./helium
    ./ironbar
    ./just.nix
    ./obsidian.nix
    ./opencode.nix
    ./neovim
    ./niri
    ./prismlauncher.nix
    ./procs.nix
    ./ripgrep.nix
    ./starship
    ./swaylock.nix
    ./tmux
    ./vesktop
    ./wl-clipboard.nix
    ./xwayland-satellite.nix
  ];
}
