version: 2

updates:
  - package-ecosystem: nix
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(flake)"
    labels:
      - dependencies
    groups:
      nixpkgs-family:
        patterns:
          - nixpkgs
          - home-manager
          - catppuccin
          - sops-nix
          - ironbar
          - nur
          - disko
          - treefmt-nix
          - helium
          - obsidian-extensions

      niri:
        patterns:
          - niri
