{
  imports = [
    ./disko.nix
    ./fifine.nix
    ./hardware.nix
    ./kernel.nix
    ./locale.nix
    ./networking.nix
    ./nvidia-prime.nix
    ./secrets.nix
    ./state-version.nix
    ./user.nix

    ../../modules/nixos/bootloader.nix
    ../../modules/nixos/console.nix
    ../../modules/nixos/default-packages.nix
    ../../modules/nixos/desktop.nix
    ../../modules/nixos/documentation.nix
    ../../modules/nixos/firewall.nix
    ../../modules/nixos/fonts.nix
    ../../modules/nixos/networking.nix
    ../../modules/nixos/nix
    ../../modules/nixos/nixpkgs.nix
    ../../modules/nixos/power.nix
    ../../modules/nixos/security.nix
    ../../modules/nixos/swap.nix
    ../../modules/nixos/hardware
    ../../modules/nixos/portals
    ../../modules/nixos/programs
    ../../modules/nixos/services
    ../../modules/nixos/systemd
    ../../modules/nixos/virtualisation
  ];
}
