context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Noise Canceling source"
            media.name       = "Noise Canceling source"
            node.name        = "rnnoise_source"
            audio.rate       = 48000
            audio.channels   = 1
            audio.position   = [ MONO ]
            capture.props = {
                node.name    = "capture.rnnoise_source"
                media.class  = Stream/Input/Audio
                node.passive = true
            }
            playback.props = {
                node.name           = "rnnoise_source"
                media.class         = Audio/Source
                filter.smart        = true
                filter.smart.target = { node.name = "alsa_input.usb-3142_Fifine_Microphone-00.mono-fallback" }
            }
            filter.graph = {
                nodes = [
                    {
                        type = ladspa
                        name = rnnoise
                        plugin = librnnoise_ladspa
                        label = noise_suppressor_mono
                        control = {
                            "VAD Threshold (%)"          = 30.0
                            "VAD Grace Period (ms)"      = 200
                            "Retroactive VAD Grace (ms)" = 0
                        }
                    }
                    {
                        type = ladspa
                        name = compressor
                        plugin = sc4m_1916
                        label = sc4m
                        control = {
                            "RMS/peak"             = 0.0
                            "Attack time (ms)"     = 5.0
                            "Release time (ms)"    = 150.0
                            "Threshold level (dB)" = -20.0
                            "Ratio (1:n)"          = 4.0
                            "Knee radius (dB)"     = 3.25
                            "Makeup gain (dB)"     = 8.0
                        }
                    }
                ]
                links = [
                    { output = "rnnoise:Output" input = "compressor:Input" }
                ]
                inputs  = [ "rnnoise:Input" ]
                outputs = [ "compressor:Output" ]
            }
        }
    }
]
