require("plugins.nvim-tree")
require("plugins.mini-tabline")
require("plugins.mini-statusline")
require("plugins.treesitter")
require("plugins.blink-cmp")
require("plugins.autopairs")
require("plugins.noice")
require("plugins.cord")
