name: Setup Nix
description: Installs Nix with flakes enabled

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
