name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/nix-format-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/nix-lint
